---
- hosts: web
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Login to Docker Hub
      docker_login:
        username: harshp01
        password: dckr_pat_teCcSYNFuFYF47Wgac7YDQDmPxc

    - name: Pull Docker image
      docker_image:
        name: harshp01/two-tier-app
        tag: latest

    - name: Run Flask app container
      docker_container:
        name: flask_app
        image: harshp01/two-tier-app
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
